apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
